# Generated by Django 5.0.3 on 2024-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('kyc_verified', models.BooleanField(default=True)),
                ('btc_wallet', models.CharField(max_length=255)),
                ('eth_wallet', models.CharField(max_length=255)),
                ('usdt_wallet', models.CharField(max_length=255)),
                ('ltc_wallet', models.CharField(max_length=255)),
                ('usdc_wallet', models.CharField(max_length=255)),
                ('doge_wallet', models.CharField(max_length=255)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
