# Generated by Django 5.0.3 on 2024-03-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proofs/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction')),
            ],
        ),
    ]
